---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
  labels:
    name: cloudflared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: tunnel-credentials
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: homelab-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "assafdori.com"
      service: http://landing-page.landing-page.svc.cluster.local:80
    - hostname: "www.assafdori.com"
      service: http://landing-page.landing-page.svc.cluster.local:80
    - hostname: "whoami.assafdori.com"
      service: http://whoami.whoami.svc.cluster.local:80
    - hostname: "uptime.assafdori.com"
      service: http://uptime-kuma.uptime-kuma.svc.cluster.local:80
    - hostname: "linkding.assafdori.com"
      service: http://linkding.linkding.svc.cluster.local:80
    - service: http_status:404
