apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-content
  namespace: landing-page
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Assaf Dori - Homelab Services</title>
        <style>
            :root {
                --primary-color: #2563eb;
                --secondary-color: #1e40af;
                --background-color: #f8fafc;
                --text-color: #1e293b;
            }
            
            body {
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                margin: 0;
                padding: 0;
                background-color: var(--background-color);
                color: var(--text-color);
                line-height: 1.6;
            }
            
            .container {
                max-width: 800px;
                margin: 0 auto;
                padding: 2rem;
            }
            
            header {
                text-align: center;
                margin-bottom: 3rem;
            }
            
            h1 {
                font-size: 2.5rem;
                margin-bottom: 0.5rem;
                color: var(--primary-color);
            }
            
            .subtitle {
                font-size: 1.2rem;
                color: #64748b;
            }
            
            .services {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 1.5rem;
                margin-top: 2rem;
            }
            
            .service-card {
                background: white;
                border-radius: 0.5rem;
                padding: 1.5rem;
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
                transition: transform 0.2s;
            }
            
            .service-card:hover {
                transform: translateY(-2px);
            }
            
            .service-card h2 {
                margin-top: 0;
                color: var(--primary-color);
            }
            
            .service-card a {
                display: inline-block;
                margin-top: 1rem;
                padding: 0.5rem 1rem;
                background-color: var(--primary-color);
                color: white;
                text-decoration: none;
                border-radius: 0.25rem;
                transition: background-color 0.2s;
            }
            
            .service-card a:hover {
                background-color: var(--secondary-color);
            }
            
            footer {
                text-align: center;
                margin-top: 3rem;
                padding-top: 2rem;
                border-top: 1px solid #e2e8f0;
                color: #64748b;
            }
            
            @media (max-width: 640px) {
                .container {
                    padding: 1rem;
                }
                
                h1 {
                    font-size: 2rem;
                }
            }
        </style>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>Assaf Dori</h1>
                <p class="subtitle">Homelab Services</p>
            </header>
            
            <div class="services">
                <div class="service-card">
                    <h2>Uptime Monitor</h2>
                    <p>Monitor the status of all my services and get instant notifications when something goes down.</p>
                    <a href="https://uptime.assafdori.com">Visit Uptime-Kuma</a>
                </div>
                
                <div class="service-card">
                    <h2>Bookmark Manager</h2>
                    <p>My personal bookmark manager for saving and organizing interesting links and resources.</p>
                    <a href="https://linkding.assafdori.com">Visit Linkding</a>
                </div>
                
                <div class="service-card">
                    <h2>Whoami Service</h2>
                    <p>A simple service for testing and debugging purposes.</p>
                    <a href="https://whoami.assafdori.com">Visit Whoami</a>
                </div>
            </div>
            
            <footer>
                <p>Powered by Kubernetes.</p>
                <p>© 2025 Assaf Dori</p>
            </footer>
        </div>
    </body>
    </html> 