apiVersion: v1
kind: Namespace
metadata:
  name: landing-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: landing-page-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: landing-page-content
        configMap:
          name: landing-page-content
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: landing-page
spec:
  selector:
    app: landing-page
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: landing-page-hpa
  namespace: landing-page
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: landing-page
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 